docs/AboutUs.md
=> [#47] Update names and roles in About Us

docs/UserGuide.md
=> [#56] Update UserGuide.md

docs/UserGuide.md
=> [#55] Update UserGuide.md

docs/UserGuide.md
=> [#57] Update UserGuide.md

docs/DeveloperGuide.md
- Product Scope
- User Stories
#50
=> [#50] Update DeveloperGuide.md

docs/DeveloperGuide.md
=> [#53] Update DeveloperGuide.md

docs/DeveloperGuide.md
=> [#51][#52] Update DeveloperGuide.md

src/main/java/seedu/address/model/task/Task.java, src/main/java/seedu/address/model/task/TaskDescription.java
=> [#91] Implement Task in Model

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/task/Task.java, src/main/java/seedu/address/model/task/TaskList.java, src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java, src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java, src/test/java/seedu/address/logic/commands/ClearPeopleCommandTest.java, src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java, src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java, src/test/java/seedu/address/logic/commands/FindPersonCommandTest.java, src/test/java/seedu/address/logic/commands/ListPeopleCommandTest.java, src/test/java/seedu/address/model/ModelManagerTest.java
=> [#91] Implement TaskList in Model and ModelManager

src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/SwitchTabContactsCommand.java, src/main/java/seedu/address/logic/commands/SwitchTabTasksCommand.java, src/main/java/seedu/address/logic/commands/taskcommand/AddTaskCommand.java, src/main/java/seedu/address/logic/parser/TaskBookParser.java, src/main/java/seedu/address/logic/parser/taskcommand/AddTaskCommandParser.java
`TaskBookParser` parses task commands, while `AddressBookParser` parses contacts commands
Other changes
- Typing contacts while on the contacts tab and tasks while on the tasks tab now gives an error
- Added skeleton for `AddTaskCommand` and `AddTaskCommandParser`, just as an example on how to include it in `TaskBookParser`. No implementation yet
=> Implement TaskBookParser

src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/TabMenu.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/TabMenu.fxml
=> Add labels at the top to better represent which tab is currently selected

src/main/java/seedu/address/logic/commands/personcommand/FindPersonCommand.java, src/main/java/seedu/address/logic/parser/personcommand/FindPersonCommandParser.java, src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/commands/FindPersonCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/FindPersonCommandParserTest.java, src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Remove zero keywords test case in FindPersonCommandTest as it does not apply to our new function
=> Add functionality to find command to search for keywords within specific categories

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/taskcommand/DeleteTaskCommand.java, src/main/java/seedu/address/logic/parser/TaskBookParser.java, src/main/java/seedu/address/logic/parser/taskcommand/DeleteTaskCommandParser.java
=> [#94] Implement Delete task command

src/main/java/seedu/address/logic/commands/taskcommand/AddTaskCommand.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/taskcommand/AddTaskCommandParser.java, src/main/java/seedu/address/model/task/TaskDescription.java
=> [#92] Implement Add task command

src/main/java/dash/logic/commands/personcommand/AddPersonCommand.java, src/main/java/dash/logic/commands/taskcommand/AddTaskCommand.java, src/main/java/dash/logic/parser/personcommand/AddPersonCommandParser.java, src/main/java/dash/logic/parser/personcommand/DeletePersonCommandParser.java, src/main/java/dash/logic/parser/personcommand/EditPersonCommandParser.java, src/main/java/dash/logic/parser/personcommand/FindPersonCommandParser.java, src/test/java/dash/logic/commands/AddPersonCommandIntegrationTest.java, src/test/java/dash/logic/commands/DeletePersonCommandTest.java, src/test/java/dash/logic/commands/EditPersonCommandTest.java, src/test/java/dash/logic/commands/FindPersonCommandTest.java, src/test/java/dash/logic/parser/DeletePersonCommandParserTest.java
=> [#106] Refactor Command Names in header comments

docs/index.md
=> Update index.md to reflect Dash

docs/UserGuide.md, src/main/java/dash/ui/HelpPanel.java
Find a way to make UG link clickable
=> Add Help Tab message and update UG clear command under Command summary

src/main/java/dash/commons/core/Messages.java, src/main/java/dash/logic/parser/personcommand/EditPersonCommandParser.java, src/main/java/dash/logic/parser/personcommand/FindPersonCommandParser.java, src/main/java/dash/logic/parser/personcommand/TagPersonCommandParser.java, src/main/java/dash/logic/parser/taskcommand/AssignPeopleCommandParser.java, src/main/java/dash/logic/parser/taskcommand/EditTaskCommandParser.java, src/main/java/dash/logic/parser/taskcommand/FindTaskCommandParser.java, src/main/java/dash/logic/parser/taskcommand/TagTaskCommandParser.java
=> Add error handling for empty arguments

src/main/java/dash/model/task/TaskDate.java
=> Fix Leniency of LocalDate#parse

src/main/java/dash/logic/commands/taskcommand/EditTaskCommand.java
- Editing of task in filtered list edits wrong task
=> Fix edit task command bug

src/main/java/dash/logic/commands/taskcommand/EditTaskCommand.java
=> Remove print statements

src/main/java/dash/logic/commands/personcommand/EditPersonCommand.java, src/main/java/dash/model/task/Task.java, src/main/java/dash/model/task/TaskList.java
- Editing person does not change the person in assigned tasks
=> Fix editing person not changing assigned person in tasks bug

src/main/java/dash/logic/commands/personcommand/DeletePersonCommand.java, src/main/java/dash/model/task/TaskList.java
- Deleting person does not delete the person in assigned tasks
=> Fix deleting person not deleting assigned person in tasks bug

src/main/java/dash/logic/commands/personcommand/DeletePersonCommand.java, src/main/java/dash/logic/commands/personcommand/EditPersonCommand.java, src/main/java/dash/logic/commands/taskcommand/EditTaskCommand.java, src/main/java/dash/model/Model.java, src/main/java/dash/model/ModelManager.java, src/test/java/dash/logic/commands/personcommand/AddPersonCommandTest.java, src/test/java/dash/logic/commands/taskcommand/AddTaskCommandTest.java
=> Improve abstraction

docs/UserGuide.md
=> Update UG Find command section to include completion status

docs/UserGuide.md, src/main/java/dash/commons/core/Messages.java, src/main/java/dash/logic/commands/personcommand/AddPersonCommand.java, src/main/java/dash/logic/commands/personcommand/ClearPeopleCommand.java, src/main/java/dash/logic/commands/personcommand/DeletePersonCommand.java, src/main/java/dash/logic/commands/personcommand/EditPersonCommand.java, src/main/java/dash/logic/commands/personcommand/FindPersonCommand.java, src/main/java/dash/logic/commands/personcommand/ListPeopleCommand.java, src/main/java/dash/logic/commands/personcommand/TagPersonCommand.java, src/main/java/dash/logic/commands/taskcommand/AddTaskCommand.java, src/main/java/dash/logic/commands/taskcommand/AssignPeopleCommand.java, src/main/java/dash/logic/commands/taskcommand/ClearDoneTaskCommand.java, src/main/java/dash/logic/commands/taskcommand/ClearTaskCommand.java, src/main/java/dash/logic/commands/taskcommand/CompleteTaskCommand.java, src/main/java/dash/logic/commands/taskcommand/DeleteTaskCommand.java, src/main/java/dash/logic/commands/taskcommand/EditTaskCommand.java, src/main/java/dash/logic/commands/taskcommand/FindTaskCommand.java, src/main/java/dash/logic/commands/taskcommand/ListTaskCommand.java, src/main/java/dash/logic/commands/taskcommand/TagTaskCommand.java, src/main/java/dash/logic/commands/taskcommand/UpcomingTaskCommand.java, src/test/java/dash/logic/commands/CommandTestUtil.java
Add punctuation to Messages
Tweak UG
Remove unused lines in CommandTestUtil
=> Change Command format messages

src/main/java/dash/commons/core/Messages.java, src/main/java/dash/logic/commands/personcommand/AddPersonCommand.java, src/main/java/dash/logic/commands/personcommand/EditPersonCommand.java
=> Tweak error messages

src/test/java/dash/logic/parser/personcommand/FindPersonCommandParserTest.java, src/test/java/dash/logic/parser/taskcommand/FindTaskCommandParserTest.java
Add more tests to FindTaskCommandParserTest
=> Add more tests to FindPersonCommandParserTest

docs/UserGuide.md
Update edit and add contact to reflect that names must be unique
Make other miscellaneous changes
=> Make cosmetic changes to UG

src/main/java/dash/model/UserInputList.java, src/main/java/dash/ui/CommandBox.java
=> Previous command access

docs/DeveloperGuide.md
Make other miscellaneous changes
=> Fix inaccuracy in implementation section

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/dash/model/tag/Tag.java
Tweak user stories
Tweak product scope
Remove NFR
Add terms to Glossary
Change Upcoming description in UG
Add a space in Tag.java
=> Change Requirements Section of DG

src/main/java/dash/logic/commands/taskcommand/ClearDoneTaskCommand.java, src/main/java/dash/logic/commands/taskcommand/CompleteTaskCommand.java, src/test/java/dash/logic/commands/CommandTestUtil.java, src/test/java/dash/logic/commands/taskcommand/ClearDoneTaskCommandTest.java, src/test/java/dash/logic/commands/taskcommand/CompleteTaskCommandTest.java, src/test/java/dash/logic/commands/taskcommand/TagTaskCommandTest.java, src/test/java/dash/logic/parser/TaskTabParserTest.java, src/test/java/dash/logic/parser/taskcommand/EditTaskCommandParserTest.java, src/test/java/dash/model/task/TaskDateAfterCurrentDatePredicateTest.java, src/test/java/dash/model/task/TaskListTest.java, src/test/java/dash/testutil/EditTaskDescriptorBuilder.java
More tests in 
- EditTaskCommandParserTest
- TaskListTest
Added tasks and task classes
- TaskTabParserTest
- TaskDateAfterCurrentDatePredicateTest
- CompleteTaskCommandTest
- ClearDoneTaskCommandTest
- TagTaskCommandTest
=> Increase test cov
